# Read the Docs configuration file
# Minimal config for projects that don't need extra packages

version: 2  # Required

# Build environment settings
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Sphinx documentation settings
sphinx:
  configuration: docs/conf.py

# No Python dependencies to install
# python:
#   install:
#     - requirements: docs/requirements.txt
